---

  - name: Deploy Application
    git:  #repo=git://codebasehq.com/conlanacapital/conlana/middleware.git
          #repo=git@codebasehq.com:conlanacapital/conlana/middleware.git
          # {{ app_repository }}
          repo=git@codebasehq.com:javdev/sails-project/sailsdemo.git
          dest={{ app_path }}
          accept_hostkey=yes
          force=yes
          recursive=no
          key_file=/home/ubuntu/.ssh/id_rsa


  - name: change permission
    file: path={{ app_path }} state=directory  owner=ubuntu group=ubuntu recurse=yes

  - name: Stopping PM2 service
    command: chdir={{app_path}} pm2 kill

  - name: Running npm install
    command: chdir={{app_path}} npm install

  - name: Restart PM2 service
    command: chdir={{app_path}} pm2 start app.js -f
