---
- name: Provision Management
  hosts: all
  sudo: yes
  remote_user: ubuntu

  vars:
    newrelic_license_key: cdcbf45869aedee500746a0212f6b433e8166e35
    newrelic_app_path: /usr/lib/node_modules/newrelic/newrelic.js
    app_path: /home/ubuntu/conlana/middleware
    app_name: conlana-middleware

  roles:
    - common
    - conlana
    - nginx
    - deploy
    - newrelic
